BASE_VALUES = {
    "Accounting": 5,
    "Animal Handling": 5,
    "Anthropology": 1,
    "Appraise": 5,
    "Archaeology": 1,
    "Charm": 15,
    "Climb": 20,
    "Computer Use": 5,
    "Credit Rating": 0,
    "Cthulhu Mythos": 0,
    "Disguise": 5,
    "Dodge": None,             # half DEX — resolved from context
    "Drive Auto": 20,
    "Electrical Repair": 10,
    "Electronics": 1,
    "Fast Talk": 5,
    "First Aid": 30,
    "History": 5,
    "Intimidate": 15,
    "Jump": 20,
    "Law": 5,
    "Library Use": 20,
    "Listen": 20,
    "Locksmith": 1,
    "Mechanical Repair": 10,
    "Medicine": 1,
    "Natural World": 10,
    "Navigate": 10,
    "Occult": 5,
    "Operate Heavy Machinery": 1,
    "Own Language": None,      # EDU% — resolved from context
    "Persuade": 10,
    "Psychoanalysis": 1,
    "Psychology": 10,
    "Ride": 5,
    "Sleight of Hand": 10,
    "Spot Hidden": 25,
    "Stealth": 20,
    "Swim": 20,
    "Throw": 20,
    "Track": 10,
}

SPECIALIZATIONS = {
    "Fighting": [
        ("Brawl", 25), ("Axe", 15), ("Chainsaw", 10), ("Flail", 10),
        ("Garrote", 15), ("Spear", 20), ("Sword", 20), ("Whip", 5),
    ],
    "Firearms": [
        ("Bow", 15), ("Handgun", 20), ("Heavy Weapons", 10),
        ("Flamethrower", 10), ("Machine Gun", 10),
        ("Rifle/Shotgun", 25), ("Submachine Gun", 15),
    ],
    "Art/Craft": [
        ("Acting", 5), ("Calligraphy", 5), ("Carpentry", 5), ("Cooking", 5),
        ("Dancing", 5), ("Fine Art", 5), ("Forgery", 5), ("Literature", 5),
        ("Morris Dancing", 5), ("Opera Singing", 5), ("Painting", 5),
        ("Photography", 5), ("Pottery", 5), ("Sculpting", 5), ("Writing", 5),
    ],
    "Pilot": [
        ("Aircraft", 1), ("Boat", 1), ("Submarine", 1),
    ],
    "Science": [
        ("Astronomy", 1), ("Biology", 1), ("Botany", 1), ("Chemistry", 1),
        ("Cryptography", 1), ("Engineering", 1), ("Forensics", 1),
        ("Geology", 1), ("Mathematics", 10), ("Meteorology", 1),
        ("Pharmacy", 1), ("Physics", 1), ("Zoology", 1),
    ],
    "Survival": [
        ("Arctic", 10), ("Desert", 10), ("Sea", 10),
    ],
    "Other Language": [],  # free text; base always 1
}

COMMON_LANGUAGES = [
    "Arabic", "Chinese", "French", "German", "Greek", "Italian",
    "Japanese", "Latin", "Portuguese", "Russian", "Spanish", "Swedish",
]

# Plain skill display name → JSON schema key
SCHEMA_KEY = {
    "Accounting": "accounting",
    "Animal Handling": "animal_handling",
    "Anthropology": "anthropology",
    "Appraise": "appraise",
    "Archaeology": "archaeology",
    "Charm": "charm",
    "Climb": "climb",
    "Computer Use": "computer_use",
    "Credit Rating": "credit_rating",
    "Cthulhu Mythos": "cthulhu_mythos",
    "Disguise": "disguise",
    "Dodge": "dodge",
    "Drive Auto": "drive_auto",
    "Electrical Repair": "electrical_repair",
    "Electronics": "electronics",
    "Fast Talk": "fast_talk",
    "First Aid": "first_aid",
    "History": "history",
    "Intimidate": "intimidate",
    "Jump": "jump",
    "Law": "law",
    "Library Use": "library_use",
    "Listen": "listen",
    "Locksmith": "locksmith",
    "Mechanical Repair": "mechanical_repair",
    "Medicine": "medicine",
    "Natural World": "natural_world",
    "Navigate": "navigate",
    "Occult": "occult",
    "Operate Heavy Machinery": "operate_heavy_machinery",
    "Own Language": "language_own",
    "Persuade": "persuade",
    "Psychoanalysis": "psychoanalysis",
    "Psychology": "psychology",
    "Ride": "ride",
    "Sleight of Hand": "sleight_of_hand",
    "Spot Hidden": "spot_hidden",
    "Stealth": "stealth",
    "Swim": "swim",
    "Throw": "throw",
    "Track": "track",
}

# Specialization group display name → JSON schema key (these become arrays)
ARRAY_GROUPS = {
    "Fighting": "fighting",
    "Firearms": "firearms",
    "Art/Craft": "art_and_craft",
    "Other Language": "language_other",
    "Pilot": "pilot",
    "Science": "science",
    "Survival": "survival",
}
