BASE_VALUES = {
    "Accounting": 5,
    "Animal Handling": 5,
    "Anthropology": 1,
    "Appraise": 5,
    "Archaeology": 1,
    "Charm": 15,
    "Climb": 20,
    "Computer Use": 5,
    "Credit Rating": 0,
    "Cthulhu Mythos": 0,
    "Disguise": 5,
    "Dodge": None,             # half DEX — resolved from context
    "Drive Auto": 20,
    "Electrical Repair": 10,
    "Electronics": 1,
    "Fast Talk": 5,
    "First Aid": 30,
    "History": 5,
    "Intimidate": 15,
    "Jump": 20,
    "Law": 5,
    "Library Use": 20,
    "Listen": 20,
    "Locksmith": 1,
    "Mechanical Repair": 10,
    "Medicine": 1,
    "Natural World": 10,
    "Navigate": 10,
    "Occult": 5,
    "Operate Heavy Machinery": 1,
    "Own Language": None,      # EDU% — resolved from context
    "Persuade": 10,
    "Psychoanalysis": 1,
    "Psychology": 10,
    "Ride": 5,
    "Sleight of Hand": 10,
    "Spot Hidden": 25,
    "Stealth": 20,
    "Swim": 20,
    "Throw": 20,
    "Track": 10,
}

SPECIALIZATIONS = {
    # Tuples are (name, base_value, weight). Weight is used when resolving
    # "ANY" — higher weight means more likely to be chosen.
    "Fighting": [
        ("Brawl", 25, 50), ("Axe", 15, 15), ("Chainsaw", 10, 4),
        ("Flail", 10, 4), ("Garrote", 15, 8), ("Spear", 20, 8),
        ("Sword", 20, 20), ("Whip", 5, 4),
    ],
    "Firearms": [
        ("Bow", 15, 10), ("Handgun", 20, 40), ("Heavy Weapons", 10, 5),
        ("Flamethrower", 10, 2), ("Machine Gun", 10, 5),
        ("Rifle/Shotgun", 25, 35), ("Submachine Gun", 15, 15),
    ],
    "Art/Craft": [
        ("Acting", 5, 15), ("Calligraphy", 5, 5), ("Carpentry", 5, 10),
        ("Cooking", 5, 10), ("Dancing", 5, 10), ("Fine Art", 5, 15),
        ("Forgery", 5, 8), ("Literature", 5, 12), ("Morris Dancing", 5, 2),
        ("Opera Singing", 5, 5), ("Painting", 5, 15), ("Photography", 5, 12),
        ("Pottery", 5, 8), ("Sculpting", 5, 8), ("Writing", 5, 12),
    ],
    "Pilot": [
        ("Aircraft", 1, 30), ("Boat", 1, 50), ("Submarine", 1, 5),
    ],
    "Science": [
        ("Astronomy", 1, 10), ("Biology", 1, 15), ("Botany", 1, 10),
        ("Chemistry", 1, 15), ("Cryptography", 1, 5), ("Engineering", 1, 10),
        ("Forensics", 1, 8), ("Geology", 1, 8), ("Mathematics", 10, 12),
        ("Meteorology", 1, 5), ("Pharmacy", 1, 10), ("Physics", 1, 10),
        ("Zoology", 1, 8),
    ],
    "Survival": [
        ("Arctic", 10, 15), ("Desert", 10, 20), ("Sea", 10, 25),
    ],
    "Other Language": [],  # free text; base always 1
}

COMMON_LANGUAGES = [
    "Arabic", "Chinese", "French", "German", "Greek", "Italian",
    "Japanese", "Latin", "Portuguese", "Russian", "Spanish", "Swedish",
]

# Plain skill display name → JSON schema key
SCHEMA_KEY = {
    "Accounting": "accounting",
    "Animal Handling": "animal_handling",
    "Anthropology": "anthropology",
    "Appraise": "appraise",
    "Archaeology": "archaeology",
    "Charm": "charm",
    "Climb": "climb",
    "Computer Use": "computer_use",
    "Credit Rating": "credit_rating",
    "Cthulhu Mythos": "cthulhu_mythos",
    "Disguise": "disguise",
    "Dodge": "dodge",
    "Drive Auto": "drive_auto",
    "Electrical Repair": "electrical_repair",
    "Electronics": "electronics",
    "Fast Talk": "fast_talk",
    "First Aid": "first_aid",
    "History": "history",
    "Intimidate": "intimidate",
    "Jump": "jump",
    "Law": "law",
    "Library Use": "library_use",
    "Listen": "listen",
    "Locksmith": "locksmith",
    "Mechanical Repair": "mechanical_repair",
    "Medicine": "medicine",
    "Natural World": "natural_world",
    "Navigate": "navigate",
    "Occult": "occult",
    "Operate Heavy Machinery": "operate_heavy_machinery",
    "Own Language": "language_own",
    "Persuade": "persuade",
    "Psychoanalysis": "psychoanalysis",
    "Psychology": "psychology",
    "Ride": "ride",
    "Sleight of Hand": "sleight_of_hand",
    "Spot Hidden": "spot_hidden",
    "Stealth": "stealth",
    "Swim": "swim",
    "Throw": "throw",
    "Track": "track",
}

# Specialization group display name → JSON schema key (these become arrays)
ARRAY_GROUPS = {
    "Fighting": "fighting",
    "Firearms": "firearms",
    "Art/Craft": "art_and_craft",
    "Other Language": "language_other",
    "Pilot": "pilot",
    "Science": "science",
    "Survival": "survival",
}
